Fixed NameError `file` on Python 3. Use `io.IOBase` instead.
